import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FirebaseProvider } from "../context/Firebase";
import Navbar from "@/components/ui/Navbar";
// import SOSGuard from "@/components/SOSGuard";
import CheckSOSActive from "@/components/CheckSOSActive";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FirebaseProvider>
          <Navbar />
          <CheckSOSActive />
          {children}
        </FirebaseProvider>
      </body>
    </html>
  );
}
